### PR TITLE
20211112 fixed sim

### PR DESCRIPTION
**Pull request by Wello-Startrii**
# Description
This repo is fork form `commaai/openpilot` to keep the version stable and workable for testing and simulation. This PR fixed some issue when simulation with Carla and openpilot.

## Fixed issue 
1. Fixed the camera operation (EON vs TICI) make the simulator could recognize the track properly.
2. Add `msg.append(packer.make_can_msg("HUD_SETTING", 0, {}, idx))` to `/tools/sim/lib/can.py` to fixed the CAN communication error issue 
3. modified the DBC file in `/opendbc/honda_civic_touring_2016_can_generated.dbc` to fixed the warning message `COUNTER is not defined` when` bridge.py` running. **Note** : This modification isn't in this repo, because `opendbc` is the submodule of `openpilot`. Please manual fixed it after clone the repo. 
```
BO_ 493 HUD_SETTING: 8 XXX
 SG_ IMPERIAL_UNIT : 5|1@0+ (1,0) [0|1] "" EON
 SG_ COUNTER : 61|2@0+ (1,0) [0|3] "" EON
 SG_ CHECKSUM : 59|4@0+ (1,0) [0|3] "" EON
```

## Function added

1. Added `can_bus_send.py ` to `/tools/can/`. Run `python can_bus_send.py <can_interface>` to send CAN message with STMCU specification from simulation.

## Setup 

1. Clone openpilot into your home directory:
```
cd ~
git clone --recurse-submodules https://github.com/Startrii/openpilot.git
 ```
and make sure all the submodule is update to latest 

2. Run the setup script:
Ubuntu 20.04 LTS:
```
openpilot/tools/ubuntu_setup.sh
```
Ensure you have a working OpenCL runtime:
You can verify your OpenCL installation with the `clinfo` command.

If you do not have any working platforms, you can download drivers from your GPU vendor's site. On Ubuntu you can just install one of the packages returned by `apt search opencl-icd.
`

3. Activate the Python environment:
Execute the following command in root openpilot directory:
```
pipenv shell
```
Your shell prompt should change to something similar to `(openpilot) user@machine:~/openpilot$ .`

Build openpilot by running SCons and set `USE_FRAME_STREAM=1` in the root of the openpilot directory
```
cd openpilot && USE_FRAME_STREAM=1 scons -j$(nproc)
```
Try out some tools!
NOTE: you can always run update_requirements.sh to pull in new python dependencies.

## Simulation 
To the directory `/tools/sim/`

First, start the CARLA server in one terminal.
```
./start_carla.sh
```

Then, start the openpilot in another terminal.
```
./launch_openpilot.sh
```
last, start the bridge in another terminal.
```
./bridge.py 
```

To engage openpilot press 1 a few times while focused on bridge.py to increase the cruise speed.

You can control openpilot driving in the simulation with the following keys

|  key  |   functionality   |
| :---: | :---------------: |
|   1   |  Cruise up 5 mph  |
|   2   | Cruise down 5 mph |
|   3   |   Cruise cancel   |
|   q   |     Exit all      |

### CODE REVIEW

**Comment by KHLee-Startrii** [comment]
```
./bridge.py
Traceback (most recent call last):
  File "./bridge.py", line 3, in <module>
    import carla # pylint: disable=import-error
ModuleNotFoundError: No module named 'carla'
```

I got this error message while I'm trying to run the module following the instructions.
I have no idea how to fix it.

**Comment by Wello-Startrii** [comment]
> ```
> ./bridge.py
> Traceback (most recent call last):
>   File "./bridge.py", line 3, in <module>
>     import carla # pylint: disable=import-error
> ModuleNotFoundError: No module named 'carla'
> ```
> 
> I got this error message while I'm trying to run the module following the instructions. I have no idea how to fix it.

`./bridge.py` is the program let openpilot run in the [CARLA simulator](https://github.com/carla-simulator/carla). So the CARLA should be install in the test device. However, CARLA works properly wiyth NVIDIA GPU as hardware requirement. I think that is difficult to test on own device. We should build a workflow with server PC.

**Comment by KHLee-Startrii** [comment]
> `./bridge.py` is the program let openpilot run in the [CARLA simulator](https://github.com/carla-simulator/carla). So the CARLA should be install in the test device. However, CARLA works properly wiyth NVIDIA GPU as hardware requirement. I think that is difficult to test on own device. We should build a workflow with server PC.

Therefore, We are basically not able to test this repo on our notebooks. I'll figure out it's structure and check if there is any obvious error.

**Review by KHLee-Startrii — APPROVED** [review]
Basically no problems. I'll also do more research on openpilot.

**Pull request merged**
